### ISSUE TITLE
testrunner doesn't find tests if main is async

### ISSUE THREAD

**Issue by zoechi** [dart-lang/unittest#15]
`pub run unittest:unittest` reports `No tests run.` when `main()` is async.

```Dart
main() async {
 test("test1", () {
   ...
 });
}
```

**Comment by nex3** [comment]
There should be a better error for this, but it is by design. An `async` function's body isn't run synchronously (even before `await`), and the test framework doesn't allow tests to be defined asynchronously, since otherwise there's no good way for it to know when they're done being defined.
