### ISSUE TITLE
Use stack_trace package to produce proper stack traces including async calls

### ISSUE THREAD

**Issue by zoechi** [dart-lang/unittest#38]
wrap the execution of each test with Chain.capture to get proper stack traces from failed tests.
It seems currently the code for each test needs to be wrapped, which is cumbersome and clutters the tests.

**Comment by zoechi** [comment]
Seems 0.12.0-alpha.1 is just doing that.

**Comment by nex3** [comment]
![](http://media2.giphy.com/media/edMvb8zy8eWDm/giphy.gif)

**Comment by zoechi** [comment]
:)
