### ISSUE TITLE
Running/debugging test in the browser has escape sequences in the console

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/unittest#41]
e.g.

      JsFunction
      notification_test.dart.js:12387 
      00:00 [32m+1[0m: constructor exists[0m
      notification_test.dart.js:12387 
      00:00 [32m+2[0m: A group of tests First Test[0m
      notification_test.dart.js:12387 
      00:00 [32m+2[0m: All tests passed![0m

**Comment by nex3** [comment]
Support for running test files directly in the browser is not planned, at least for the near-to-mid future. Browser tests should be run through the test runner.

**Comment by alan-knight** [comment]
So if I understand the story as it is in the short term.
  - There is no support for debugging tests from the runner  
  - Running tests manually to debug them is discouraged.

The debugging story is run it directly unsupported? Copy and paste it out of the test into somewhere else and debug that? What do we expect to do for things that use unittest but have their own runner. e.g. all current SDK tests.

**Comment by nex3** [comment]
*All* debugging stories for browser tests are currently unsupported. That's why #45 is still open. We're still in alpha releases of a pre-1.0.0 version of a complete rewrite of the testing framework—we need to lay a bunch of groundwork before we can start building on it.
