### ISSUE TITLE
A way of printing the reproduction instructions for a browser test would be helpful

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/unittest#43]
In the dart repo testing tool, when a test fails, you get a bunch of verbiage which includes 
  - command line to recompile the sources
  - command line to run a server
  - command line to launch the browser and connect to the server

It's a bit painful, but lets you re-run the test and debug it in the browser. For bonus points, something that re-ran the test itself but inserted a debugger() at the beginning of the failing test would be awesome.

**Comment by nex3** [comment]
We definitely want to have a good debugging story for browser tests, although it's not in the plans for 0.12.0. I don't think making the user manually compile a test file and start a server is the best way to do it; the runner itself should handle that as much as possible.

I'll retarget this as #45.
